run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    # Test files - ignore unchecked errors in tests
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - ineffassign

    # Non-test files - ignore these specific linters in certain contexts
    - path: internal/replication/rdb\.go
      linters:
        - errcheck
